/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as swagger from "@nestjs/swagger";
import { isRecordNotFoundError } from "../../prisma.util";
import * as errors from "../../errors";
import { Request } from "express";
import { plainToClass } from "class-transformer";
import { ApiNestedQuery } from "../../decorators/api-nested-query.decorator";
import { AsdaService } from "../asda.service";
import { AsdaCreateInput } from "./AsdaCreateInput";
import { Asda } from "./Asda";
import { AsdaFindManyArgs } from "./AsdaFindManyArgs";
import { AsdaWhereUniqueInput } from "./AsdaWhereUniqueInput";
import { AsdaUpdateInput } from "./AsdaUpdateInput";

export class AsdaControllerBase {
  constructor(protected readonly service: AsdaService) {}
  @common.Post()
  @swagger.ApiCreatedResponse({ type: Asda })
  async createAsda(@common.Body() data: AsdaCreateInput): Promise<Asda> {
    return await this.service.createAsda({
      data: data,
      select: {
        createdAt: true,
        description: true,
        email: true,
        firstName: true,
        id: true,
        isActive: true,
        name: true,
        startDate: true,
        updatedAt: true,
      },
    });
  }

  @common.Get()
  @swagger.ApiOkResponse({ type: [Asda] })
  @ApiNestedQuery(AsdaFindManyArgs)
  async asdas(@common.Req() request: Request): Promise<Asda[]> {
    const args = plainToClass(AsdaFindManyArgs, request.query);
    return this.service.asdas({
      ...args,
      select: {
        createdAt: true,
        description: true,
        email: true,
        firstName: true,
        id: true,
        isActive: true,
        name: true,
        startDate: true,
        updatedAt: true,
      },
    });
  }

  @common.Get("/:id")
  @swagger.ApiOkResponse({ type: Asda })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async asda(
    @common.Param() params: AsdaWhereUniqueInput
  ): Promise<Asda | null> {
    const result = await this.service.asda({
      where: params,
      select: {
        createdAt: true,
        description: true,
        email: true,
        firstName: true,
        id: true,
        isActive: true,
        name: true,
        startDate: true,
        updatedAt: true,
      },
    });
    if (result === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return result;
  }

  @common.Patch("/:id")
  @swagger.ApiOkResponse({ type: Asda })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async updateAsda(
    @common.Param() params: AsdaWhereUniqueInput,
    @common.Body() data: AsdaUpdateInput
  ): Promise<Asda | null> {
    try {
      return await this.service.updateAsda({
        where: params,
        data: data,
        select: {
          createdAt: true,
          description: true,
          email: true,
          firstName: true,
          id: true,
          isActive: true,
          name: true,
          startDate: true,
          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Delete("/:id")
  @swagger.ApiOkResponse({ type: Asda })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async deleteAsda(
    @common.Param() params: AsdaWhereUniqueInput
  ): Promise<Asda | null> {
    try {
      return await this.service.deleteAsda({
        where: params,
        select: {
          createdAt: true,
          description: true,
          email: true,
          firstName: true,
          id: true,
          isActive: true,
          name: true,
          startDate: true,
          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }
}
