/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import { PrismaService } from "../../prisma/prisma.service";
import { Prisma, Asda as PrismaAsda } from "@prisma/client";

export class AsdaServiceBase {
  constructor(protected readonly prisma: PrismaService) {}

  async count(args: Omit<Prisma.AsdaCountArgs, "select">): Promise<number> {
    return this.prisma.asda.count(args);
  }

  async asdas(args: Prisma.AsdaFindManyArgs): Promise<PrismaAsda[]> {
    return this.prisma.asda.findMany(args);
  }
  async asda(args: Prisma.AsdaFindUniqueArgs): Promise<PrismaAsda | null> {
    return this.prisma.asda.findUnique(args);
  }
  async createAsda(args: Prisma.AsdaCreateArgs): Promise<PrismaAsda> {
    return this.prisma.asda.create(args);
  }
  async updateAsda(args: Prisma.AsdaUpdateArgs): Promise<PrismaAsda> {
    return this.prisma.asda.update(args);
  }
  async deleteAsda(args: Prisma.AsdaDeleteArgs): Promise<PrismaAsda> {
    return this.prisma.asda.delete(args);
  }
}
