/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as graphql from "@nestjs/graphql";
import { GraphQLError } from "graphql";
import { isRecordNotFoundError } from "../../prisma.util";
import { MetaQueryPayload } from "../../util/MetaQueryPayload";
import { Asda } from "./Asda";
import { AsdaCountArgs } from "./AsdaCountArgs";
import { AsdaFindManyArgs } from "./AsdaFindManyArgs";
import { AsdaFindUniqueArgs } from "./AsdaFindUniqueArgs";
import { CreateAsdaArgs } from "./CreateAsdaArgs";
import { UpdateAsdaArgs } from "./UpdateAsdaArgs";
import { DeleteAsdaArgs } from "./DeleteAsdaArgs";
import { AsdaService } from "../asda.service";
@graphql.Resolver(() => Asda)
export class AsdaResolverBase {
  constructor(protected readonly service: AsdaService) {}

  async _asdasMeta(
    @graphql.Args() args: AsdaCountArgs
  ): Promise<MetaQueryPayload> {
    const result = await this.service.count(args);
    return {
      count: result,
    };
  }

  @graphql.Query(() => [Asda])
  async asdas(@graphql.Args() args: AsdaFindManyArgs): Promise<Asda[]> {
    return this.service.asdas(args);
  }

  @graphql.Query(() => Asda, { nullable: true })
  async asda(@graphql.Args() args: AsdaFindUniqueArgs): Promise<Asda | null> {
    const result = await this.service.asda(args);
    if (result === null) {
      return null;
    }
    return result;
  }

  @graphql.Mutation(() => Asda)
  async createAsda(@graphql.Args() args: CreateAsdaArgs): Promise<Asda> {
    return await this.service.createAsda({
      ...args,
      data: args.data,
    });
  }

  @graphql.Mutation(() => Asda)
  async updateAsda(@graphql.Args() args: UpdateAsdaArgs): Promise<Asda | null> {
    try {
      return await this.service.updateAsda({
        ...args,
        data: args.data,
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }

  @graphql.Mutation(() => Asda)
  async deleteAsda(@graphql.Args() args: DeleteAsdaArgs): Promise<Asda | null> {
    try {
      return await this.service.deleteAsda(args);
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }
}
